import os
import re
import time
import logging
from langchain_openai import ChatOpenAI
from core.config import load_config

logger = logging.getLogger(__name__)

MAX_RETRIES = 10
RETRY_DELAY = 2


def response_text(content):
    """Normalize text content returned by OpenAI-compatible endpoints."""
    if isinstance(content, str):
        return content.strip()
    if isinstance(content, list):
        return "".join(
            str(block.get("text", "")) if isinstance(block, dict) else str(block)
            for block in content
        ).strip()
    return str(content or "").strip()


def extract_sql_response(content, allow_request_denied=False):
    """Extract the final one-line SQL/denial from a reasoning-heavy response.

    Qwen can occasionally place preserved reasoning in ``content`` even when
    asked for raw SQL. We select the final visible directive and still leave
    authorization and SQL validation to the database policy layer.
    """
    text = response_text(content)
    if not text:
        return ""

    visible = text.rsplit("</think>", 1)[-1].strip()
    fenced = re.findall(r"```(?:sql)?\s*(.*?)```", visible, re.IGNORECASE | re.DOTALL)
    if fenced:
        visible = fenced[-1].strip()

    if allow_request_denied:
        denials = list(
            re.finditer(r"(?im)^\s*(REQUEST_DENIED:[^\r\n]*)", visible)
        )
        if denials:
            return denials[-1].group(1).strip().strip("`")

    # SQL generated by these agents is intentionally constrained to one line.
    # Taking the last SELECT line handles preambles and repeated self-checks
    # without executing the reasoning text itself.
    candidates = list(re.finditer(r"(?im)^\s*(SELECT\b[^\r\n]*)", visible))
    if not candidates and visible != text:
        candidates = list(re.finditer(r"(?im)^\s*(SELECT\b[^\r\n]*)", text))
    if candidates:
        sql = candidates[-1].group(1).strip()
        sql = sql.strip("`").strip()
        if sql.endswith(";"):
            return sql
        return sql

    # Return the final visible text so policy enforcement produces an explicit
    # denial rather than silently turning an invalid model response into SQL.
    return visible.strip("`").strip()


def get_llm(config=None, **overrides):
    if config is None:
        config = load_config()

    api_key = config.model.api_key
    if api_key.startswith("${") and api_key.endswith("}"):
        env_var = api_key[2:-1]
        api_key = os.environ.get(env_var, "")
        if not api_key:
            raise RuntimeError(f"Environment variable {env_var} is not set. Export it first.")

    return ChatOpenAI(
        base_url=config.model.base_url,
        api_key=api_key,
        model=config.model.model_name,
        temperature=overrides.pop("temperature", config.model.temperature),
        max_tokens=overrides.pop("max_tokens", config.model.max_tokens),
        max_retries=overrides.pop("max_retries", 0),
        request_timeout=overrides.pop("request_timeout", 120),
        **overrides,
    )


def invoke_with_retry(llm, messages, max_retries=MAX_RETRIES):
    """Invoke LLM with fixed-interval retry for content filter and transient errors."""
    for attempt in range(max_retries + 1):
        try:
            return llm.invoke(messages)
        except Exception as e:
            err_str = str(e).lower()
            is_retryable = (
                "429" in err_str
                or "rate limit" in err_str
                or "too many requests" in err_str
                or "server error" in err_str
                or "500" in err_str
                or "502" in err_str
                or "503" in err_str
                or "504" in err_str
                or "timeout" in err_str
                or "content filter" in err_str
                or "content_filter" in err_str
                or "responsibleaipolicy" in err_str
            )
            if is_retryable and attempt < max_retries:
                logger.warning(
                    "LLM call failed (attempt %d/%d): %s — retrying in %ds",
                    attempt + 1, max_retries + 1, str(e)[:200], RETRY_DELAY,
                )
                time.sleep(RETRY_DELAY)
            else:
                raise
